title: Website
logo: /assets/img/logo.png
description: Sjabloon voor een website met GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
author: Kees de Keijzer
github_username: keesdekeijzer
plugins:
  # Other plugins go here
 - jekyll-paginate

paginate: 10
paginate_path: "/posts/page:num/"
repo: website
rssfeed: feed.xml
