title: Website
logo: /assets/img/logo.png
description: Website met GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Kees de Keijzer
github_username: keesdekeijzer
